package com.ajanuary.afid;

import java.util.random.RandomGenerator;
import java.util.regex.Pattern;

/**
 * Generates random afids with a given variant and prefix.
 *
 * @see AFID
 */
public class Generator {

  private static final int MAX_LEN = 48;
  private static final int TAG_LEN = 5;
  private static final Pattern PREFIX_REGEX = Pattern.compile("^[a-z0-9-]+$");
  private static final char[] BASE32_ALPHABET =
      new char[] {
        '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h',
        'j', 'k', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'
      };

  private final RandomGenerator random;
  private final Variant variant;
  private final String prefix;

  Generator(RandomGenerator random, Variant variant, String prefix) {
    validateParams(variant, prefix);
    this.random = random;
    this.variant = variant;
    this.prefix = prefix;
  }

  private void validateParams(Variant variant, String prefix) {
    if (prefix.isEmpty()) {
      throw new IllegalArgumentException("prefix must not be empty");
    }

    int maxPrefixLen = MAX_LEN - TAG_LEN - variant.suffixLength() - 2;
    if (prefix.length() > maxPrefixLen) {
      throw new IllegalArgumentException(
          "prefix cannot be longer than " + maxPrefixLen + " characters");
    }

    if (!PREFIX_REGEX.matcher(prefix).matches()) {
      throw new IllegalArgumentException(
          "prefix can only contain lowercase letters, numbers, or -");
    }
  }

  /**
   * @return the variant of afid ids that will be generated by {@link #next()}
   */
  public Variant variant() {
    return variant;
  }

  /**
   * @return the string this generator will prefix to the afid ids generated by {@link #next()}
   */
  public String prefix() {
    return prefix;
  }

  /**
   * @return a random afid id with the variant and prefix this generator is configured for
   */
  public String next() {
    char[] idChars = new char[prefix.length() + 1 + TAG_LEN + 1 + variant.suffixLength()];

    prefix.getChars(0, prefix.length(), idChars, 0);
    idChars[prefix.length()] = '-';
    generate5Chars(idChars, prefix.length() + 1);
    idChars[prefix.length() + TAG_LEN + 1] = '-';
    generate5Chars(idChars, prefix.length() + 1 + TAG_LEN + 1);
    generate5Chars(idChars, prefix.length() + 1 + TAG_LEN + 1 + 5);
    if (variant == Variant.LONG) {
      generate5Chars(idChars, prefix.length() + 1 + TAG_LEN + 1 + 10);
      generate5Chars(idChars, prefix.length() + 1 + TAG_LEN + 1 + 15);
    }
    return new String(idChars);
  }

  private void generate5Chars(char[] dest, int destOffset) {
    int src = random.nextInt();
    dest[destOffset] = BASE32_ALPHABET[(src & 0x001F00000) >>> 20];
    dest[destOffset + 1] = BASE32_ALPHABET[(src & 0x000F8000) >>> 15];
    dest[destOffset + 2] = BASE32_ALPHABET[(src & 0x00007C00) >>> 10];
    dest[destOffset + 3] = BASE32_ALPHABET[(src & 0x000003E0) >>> 5];
    dest[destOffset + 4] = BASE32_ALPHABET[(src & 0x0000001F)];
  }
}
