package com.ajanuary.afidgen;

import java.util.Objects;
import java.util.random.RandomGenerator;
import java.util.stream.Stream;

/**
 * Generates random afids with a fixed prefix and suffix length.
 *
 * <p>The prefix is validated once when the {@code Generator} is constructed, so reusing a single
 * instance to produce many ids avoids re-validating on every call.
 *
 * <p>Thread-safety: a {@code Generator} is safe to share across threads if and only if the {@link
 * RandomGenerator} it was constructed with is. Generators created via the no-{@code
 * RandomGenerator} factories in {@link AFID} ({@link AFID#shortGenerator(String)}, {@link
 * AFID#longGenerator(String)}) use {@link java.security.SecureRandom} and are therefore
 * thread-safe. When you supply your own source, {@link java.util.Random}, {@link
 * java.security.SecureRandom}, and {@link java.util.concurrent.ThreadLocalRandom} are thread-safe;
 * {@link java.util.SplittableRandom} is not.
 *
 * @see AFID
 */
public final class Generator {

  private final RandomGenerator random;
  private final String prefix;
  private final int suffixLength;

  Generator(RandomGenerator random, String prefix, int suffixLength) {
    Objects.requireNonNull(random, "random");
    Generators.validatePrefix(prefix);
    this.random = random;
    this.prefix = prefix;
    this.suffixLength = suffixLength;
  }

  /**
   * @return the string this generator will prefix to the afid ids generated by {@link #next()}
   */
  public String prefix() {
    return prefix;
  }

  /**
   * @return a random afid id with the prefix and suffix length this generator is configured for
   */
  public String next() {
    return Generators.generate(random, prefix, suffixLength);
  }

  /**
   * @return an infinite, sequential, unordered stream of random afid ids with the prefix and suffix
   *     length this generator is configured for. Callers should use {@link Stream#limit} (or
   *     similar) to bound the stream. The returned stream is sequential by default; calling {@link
   *     Stream#parallel()} on it would invoke {@link #next()} concurrently — see the class-level
   *     thread-safety note.
   */
  public Stream<String> stream() {
    return Stream.generate(this::next);
  }
}
